spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ieadalpe_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  security:
    jwt:
      secret: 12345678901234567890123456789012
      issuer: ieadalpeapi
      expiration: 7200